var buttonColours = ['red', 'blue', 'green', 'yellow'];

//Level starts at 0
var level = 0;

//Triggers game to start and go into nextSequence
var started = false;

//Pattern generated by game
var gamePattern = [];

//User's pattern entered
var userClickedPattern = [];

//Call nextSequence once keyboard key is pressed
$(document).keypress(function() {
  if (!started) {
    $('#level-title').text('Level ' + level);
    nextSequence();
    started = true;
  }
});

//when a class '.btn' is selected apply event handler, '.click()' to execute everytime event is triggered
$('.btn').click(function() {
  //get attribute value of element
  var userChosenColour = $(this).attr('id');
  //add attribute value to userPattern
  userClickedPattern.push(userChosenColour);
  playSound(userChosenColour);
  animatePress(userChosenColour);
  //Call checkAnswer() after user has chosen their answer, passing in last number of users index to compare to gamePattern
  checkAnswer(userClickedPattern.length - 1);
});

function checkAnswer(currentLevel) {
  //Checks if userClickedPattern matches gamePattern
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {
    //Checks if user entered in full statement
    if (userClickedPattern.length === gamePattern.length) {
      //Calls nextSequence with 1000ms delay
      setTimeout(function() {
        nextSequence();
      }, 1000);
    }
  } else {
    //Sound when user enters wrong answer
    playSound('wrong');
    //Applies class game-over then removes it
    $('body').addClass('game-over');
    setTimeout(function() {
      $('body').removeClass('game-over');
    }, 200);
    //Title Changes, asks user to restart
    $('#level-title').text('Game Over, Press Any Key to Restart');
    //Call startOver function
    startOver();
  }
}

//nextSequence generates gamePattern player must attempt to replicate
function nextSequence() {
  //Reset userClickedPattern to empty array ready for next level
  userClickedPattern = [];
  //Level Up everytime nextSequence is called
  level++;
  //Changes title after a keyboard key is pressed on start page
  $('#level-title').text('Level ' + level);
  //Generate random number 0-3
  var randomNumber = Math.floor(Math.random() * 4);
  //randomNumber chooses colour from array of buttonColours
  var randomChosenColour = buttonColours[randomNumber];
  //randomChosenColour gets pushed into new array gamePattern
  gamePattern.push(randomChosenColour);
  //Use jQuery to animate randomChosenColour to fadeIn and fadeOut
  $('#' + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  //Add audio to randomChosenColour based on buttonColours
  playSound(randomChosenColour);
}

//Plays sound everytime button is activated
function playSound(name) {
  var audio = new Audio('sounds/' + name + '.mp3');
  audio.play();
}

//Animates button selected by user
function animatePress(currentColour) {
  $('#' + currentColour).addClass('pressed');
  setTimeout(function() {
    $('#' + currentColour).removeClass('pressed');
  }, 100);
}

//Reset game and start over
function startOver() {
  //Reset level
  level = 0;
  //Reset gamePattern
  gamePattern = [];
  //Reset Game
  // $(document).keypress(started = false);
  started = false;
}
